"""Add isbn,year and cover field into Book model

Revision ID: d71eef0cb4b8
Revises: 
Create Date: 2024-09-16 19:11:05.552382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd71eef0cb4b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.String(length=13), nullable=True))
        batch_op.add_column(sa.Column('publication_year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cover_image', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('cover_image')
        batch_op.drop_column('publication_year')
        batch_op.drop_column('isbn')

    # ### end Alembic commands ###
